import type { UnifiedPullRequest } from '$lib/types';

const now = new Date();
const ago = (minutes: number): string => new Date(now.getTime() - minutes * 60_000).toISOString();

export const demoPullRequests: readonly UnifiedPullRequest[] = [
  {
    id: 'github-pr-demo-1',
    source: 'github',
    title: 'feat: add dark mode support for dashboard components',
    repository: 'acme/frontend',
    url: 'https://github.com/acme/frontend/pull/342',
    number: 342,
    draft: false,
    author: { login: 'sarah-chen', avatarUrl: '' },
    createdAt: ago(120),
    updatedAt: ago(3),
    ciStatus: 'success',
    reviewDecision: 'review_required',
    reviewRequestedFromMe: true
  },
  {
    id: 'gitlab-mr-demo-2',
    source: 'gitlab',
    title: 'fix: resolve race condition in webhook processor',
    repository: 'platform/event-bus',
    url: 'https://gitlab.com/platform/event-bus/-/merge_requests/87',
    number: 87,
    draft: false,
    author: { login: 'mwilliams', avatarUrl: '' },
    createdAt: ago(240),
    updatedAt: ago(8),
    ciStatus: 'pending',
    reviewDecision: 'approved',
    reviewRequestedFromMe: true,
  },
  {
    id: 'github-pr-demo-3',
    source: 'github',
    title: 'refactor: migrate auth middleware to edge runtime',
    repository: 'acme/frontend',
    url: 'https://github.com/acme/frontend/pull/339',
    number: 339,
    draft: false,
    author: { login: 'you', avatarUrl: '' },
    createdAt: ago(480),
    updatedAt: ago(25),
    ciStatus: 'success',
    reviewDecision: 'approved',
    reviewRequestedFromMe: false,
  },
  {
    id: 'github-pr-demo-4',
    source: 'github',
    title: 'fix: correct timezone handling in scheduled reports',
    repository: 'acme/api-gateway',
    url: 'https://github.com/acme/api-gateway/pull/512',
    number: 512,
    draft: true,
    author: { login: 'you', avatarUrl: '' },
    createdAt: ago(720),
    updatedAt: ago(60),
    ciStatus: 'failure',
    reviewDecision: 'changes_requested',
    reviewRequestedFromMe: false,
  },
  {
    id: 'gitlab-mr-demo-5',
    source: 'gitlab',
    title: 'feat: add OpenTelemetry tracing to ingestion pipeline',
    repository: 'platform/data-layer',
    url: 'https://gitlab.com/platform/data-layer/-/merge_requests/198',
    number: 198,
    draft: false,
    author: { login: 'you', avatarUrl: '' },
    createdAt: ago(3000),
    updatedAt: ago(200),
    ciStatus: 'success',
    reviewDecision: 'review_required',
    reviewRequestedFromMe: false,
  }
];
